[
package
]
name = "real-time-chat"
version = "0.1.0"
edition = "2021"

[
dependencies
]
# Web framework
axum = "0.7.2"
tokio = { version = "1", features = ["full"] }

# WebSocket support
axum-websockets = "0.4.1"

# Authentication
jsonwebtoken = "8.3.0"
bcrypt = "0.10.1"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "uuid"] }
sqlx-core = "0.7"
uuid = { version = "1.6", features = ["v4"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# File handling
mime_guess = "2.0"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Other utilities
dotenv = "0.15"
color-eyre = "0.6"